server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://$SHORTENER_URL/api/;
    }

    location / {
        try_files $uri $uri/ @redirector;
    }

    location @redirector {
        proxy_pass http://$REDIRECTOR_URL;
    }
}
