services:
  frontend:
    build: frontend
    ports: 
      - 80:80
    depends_on:
      - shortener

  shortener:
    build: shortener
    ports: 
      - 5000:8080
 
  redirector:
    build: redirector
    ports:
      - 5001:8080
    depends_on:
      - urlstore_pg

  urlstore_pg:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data:
